/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as ProblemsProblemIdRouteImport } from './routes/problems.$problemId'
import { Route as DevLanguageSelectorRouteImport } from './routes/dev.language-selector'
import { Route as SessionsSessionIdFeedbackRouteImport } from './routes/sessions.$sessionId.feedback'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRoomsIndexRoute = AppRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProblemsIndexRoute = AppProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DevLanguageSelectorRoute = DevLanguageSelectorRouteImport.update({
  id: '/dev/language-selector',
  path: '/dev/language-selector',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdFeedbackRoute =
  SessionsSessionIdFeedbackRouteImport.update({
    id: '/sessions/$sessionId/feedback',
    path: '/sessions/$sessionId/feedback',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRoute
  '/dev/language-selector': typeof DevLanguageSelectorRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/problems/': typeof ProblemsIndexRoute
  '/sessions/$sessionId/feedback': typeof SessionsSessionIdFeedbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRoute
  '/dev/language-selector': typeof DevLanguageSelectorRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/problems': typeof ProblemsIndexRoute
  '/sessions/$sessionId/feedback': typeof SessionsSessionIdFeedbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRoute
  '/dev/language-selector': typeof DevLanguageSelectorRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/problems/': typeof ProblemsIndexRoute
  '/sessions/$sessionId/feedback': typeof SessionsSessionIdFeedbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/dashboard'
    | '/profile'
    | '/login'
    | '/register'
    | '/rooms'
    | '/dev/language-selector'
    | '/problems/$problemId'
    | '/rooms/$roomId'
    | '/rooms/create'
    | '/problems/'
    | '/rooms/'
    | '/sessions/$sessionId/feedback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/dashboard'
    | '/profile'
    | '/login'
    | '/register'
    | '/rooms'
    | '/dev/language-selector'
    | '/problems/$problemId'
    | '/rooms/$roomId'
    | '/rooms/create'
    | '/problems'
    | '/rooms'
    | '/sessions/$sessionId/feedback'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/problems'
    | '/register'
    | '/rooms'
    | '/dev/language-selector'
    | '/problems/$problemId'
    | '/problems/'
    | '/sessions/$sessionId/feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProblemsRoute: typeof ProblemsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  RoomsRoute: typeof RoomsRoute
  DevLanguageSelectorRoute: typeof DevLanguageSelectorRoute
  SessionsSessionIdFeedbackRoute: typeof SessionsSessionIdFeedbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/bookmarks': {
      id: '/_app/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rooms/': {
      id: '/_app/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AppRoomsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/problems/': {
      id: '/_app/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof AppProblemsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rooms/create': {
      id: '/_app/rooms/create'
      path: '/rooms/create'
      fullPath: '/rooms/create'
      preLoaderRoute: typeof AppRoomsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rooms/$roomId': {
      id: '/_app/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AppRoomsRoomIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/problems/$problemId': {
      id: '/_app/problems/$problemId'
      path: '/problems/$problemId'
      fullPath: '/problems/$problemId'
      preLoaderRoute: typeof AppProblemsProblemIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/dev/language-selector': {
      id: '/dev/language-selector'
      path: '/dev/language-selector'
      fullPath: '/dev/language-selector'
      preLoaderRoute: typeof DevLanguageSelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/feedback': {
      id: '/sessions/$sessionId/feedback'
      path: '/sessions/$sessionId/feedback'
      fullPath: '/sessions/$sessionId/feedback'
      preLoaderRoute: typeof AppSessionsSessionIdFeedbackRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProblemsProblemIdRoute: typeof AppProblemsProblemIdRoute
  AppRoomsRoomIdRoute: typeof AppRoomsRoomIdRoute
  AppRoomsCreateRoute: typeof AppRoomsCreateRoute
  AppProblemsIndexRoute: typeof AppProblemsIndexRoute
  AppRoomsIndexRoute: typeof AppRoomsIndexRoute
  AppSessionsSessionIdFeedbackRoute: typeof AppSessionsSessionIdFeedbackRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBookmarksRoute: AppBookmarksRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppProblemsProblemIdRoute: AppProblemsProblemIdRoute,
  AppRoomsRoomIdRoute: AppRoomsRoomIdRoute,
  AppRoomsCreateRoute: AppRoomsCreateRoute,
  AppProblemsIndexRoute: AppProblemsIndexRoute,
  AppRoomsIndexRoute: AppRoomsIndexRoute,
  AppSessionsSessionIdFeedbackRoute: AppSessionsSessionIdFeedbackRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProblemsRoute: ProblemsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  RoomsRoute: RoomsRoute,
  DevLanguageSelectorRoute: DevLanguageSelectorRoute,
  SessionsSessionIdFeedbackRoute: SessionsSessionIdFeedbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
