/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBookmarksRouteImport } from './routes/_app/bookmarks'
import { Route as AppRoomsRouteRouteImport } from './routes/_app/rooms/route'
import { Route as AppRoomsIndexRouteImport } from './routes/_app/rooms/index'
import { Route as AppProblemsIndexRouteImport } from './routes/_app/problems.index'
import { Route as AppSessionsSessionIdRouteImport } from './routes/_app/sessions.$sessionId'
import { Route as AppRoomsCreateRouteImport } from './routes/_app/rooms_.create'
import { Route as AppRoomsRoomIdRouteImport } from './routes/_app/rooms_.$roomId'
import { Route as AppRoomsBrowseRouteImport } from './routes/_app/rooms/browse'
import { Route as AppProblemsProblemIdRouteImport } from './routes/_app/problems.$problemId'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin.users'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRoomsRouteRoute = AppRoomsRouteRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRoomsIndexRoute = AppRoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoomsRouteRoute,
} as any)
const AppProblemsIndexRoute = AppProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRoomsCreateRoute = AppRoomsCreateRouteImport.update({
  id: '/rooms_/create',
  path: '/rooms/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRoomsRoomIdRoute = AppRoomsRoomIdRouteImport.update({
  id: '/rooms_/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRoomsBrowseRoute = AppRoomsBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AppRoomsRouteRoute,
} as any)
const AppProblemsProblemIdRoute = AppProblemsProblemIdRouteImport.update({
  id: '/problems/$problemId',
  path: '/problems/$problemId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/rooms': typeof AppRoomsRouteRouteWithChildren
  '/bookmarks': typeof AppBookmarksRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/problems/$problemId': typeof AppProblemsProblemIdRoute
  '/rooms/browse': typeof AppRoomsBrowseRoute
  '/rooms/$roomId': typeof AppRoomsRoomIdRoute
  '/rooms/create': typeof AppRoomsCreateRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/problems/': typeof AppProblemsIndexRoute
  '/rooms/': typeof AppRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/bookmarks': typeof AppBookmarksRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/problems/$problemId': typeof AppProblemsProblemIdRoute
  '/rooms/browse': typeof AppRoomsBrowseRoute
  '/rooms/$roomId': typeof AppRoomsRoomIdRoute
  '/rooms/create': typeof AppRoomsCreateRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/problems': typeof AppProblemsIndexRoute
  '/rooms': typeof AppRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_app/rooms': typeof AppRoomsRouteRouteWithChildren
  '/_app/bookmarks': typeof AppBookmarksRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/problems/$problemId': typeof AppProblemsProblemIdRoute
  '/_app/rooms/browse': typeof AppRoomsBrowseRoute
  '/_app/rooms_/$roomId': typeof AppRoomsRoomIdRoute
  '/_app/rooms_/create': typeof AppRoomsCreateRoute
  '/_app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/_app/problems/': typeof AppProblemsIndexRoute
  '/_app/rooms/': typeof AppRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rooms'
    | '/bookmarks'
    | '/dashboard'
    | '/profile'
    | '/login'
    | '/register'
    | '/admin/users'
    | '/problems/$problemId'
    | '/rooms/browse'
    | '/rooms/$roomId'
    | '/rooms/create'
    | '/sessions/$sessionId'
    | '/problems/'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/dashboard'
    | '/profile'
    | '/login'
    | '/register'
    | '/admin/users'
    | '/problems/$problemId'
    | '/rooms/browse'
    | '/rooms/$roomId'
    | '/rooms/create'
    | '/sessions/$sessionId'
    | '/problems'
    | '/rooms'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/rooms'
    | '/_app/bookmarks'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_public/login'
    | '/_public/register'
    | '/_public/'
    | '/_app/admin/users'
    | '/_app/problems/$problemId'
    | '/_app/rooms/browse'
    | '/_app/rooms_/$roomId'
    | '/_app/rooms_/create'
    | '/_app/sessions/$sessionId'
    | '/_app/problems/'
    | '/_app/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/bookmarks': {
      id: '/_app/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rooms/': {
      id: '/_app/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AppRoomsIndexRouteImport
      parentRoute: typeof AppRoomsRouteRoute
    }
    '/_app/problems/': {
      id: '/_app/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof AppProblemsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sessions/$sessionId': {
      id: '/_app/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rooms_/create': {
      id: '/_app/rooms_/create'
      path: '/rooms/create'
      fullPath: '/rooms/create'
      preLoaderRoute: typeof AppRoomsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rooms_/$roomId': {
      id: '/_app/rooms_/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AppRoomsRoomIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rooms/browse': {
      id: '/_app/rooms/browse'
      path: '/browse'
      fullPath: '/rooms/browse'
      preLoaderRoute: typeof AppRoomsBrowseRouteImport
      parentRoute: typeof AppRoomsRouteRoute
    }
    '/_app/problems/$problemId': {
      id: '/_app/problems/$problemId'
      path: '/problems/$problemId'
      fullPath: '/problems/$problemId'
      preLoaderRoute: typeof AppProblemsProblemIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRoomsRouteRouteChildren {
  AppRoomsBrowseRoute: typeof AppRoomsBrowseRoute
  AppRoomsIndexRoute: typeof AppRoomsIndexRoute
}

const AppRoomsRouteRouteChildren: AppRoomsRouteRouteChildren = {
  AppRoomsBrowseRoute: AppRoomsBrowseRoute,
  AppRoomsIndexRoute: AppRoomsIndexRoute,
}

const AppRoomsRouteRouteWithChildren = AppRoomsRouteRoute._addFileChildren(
  AppRoomsRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppRoomsRouteRoute: typeof AppRoomsRouteRouteWithChildren
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppProblemsProblemIdRoute: typeof AppProblemsProblemIdRoute
  AppRoomsRoomIdRoute: typeof AppRoomsRoomIdRoute
  AppRoomsCreateRoute: typeof AppRoomsCreateRoute
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRoute
  AppProblemsIndexRoute: typeof AppProblemsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppRoomsRouteRoute: AppRoomsRouteRouteWithChildren,
  AppBookmarksRoute: AppBookmarksRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppProblemsProblemIdRoute: AppProblemsProblemIdRoute,
  AppRoomsRoomIdRoute: AppRoomsRoomIdRoute,
  AppRoomsCreateRoute: AppRoomsCreateRoute,
  AppSessionsSessionIdRoute: AppSessionsSessionIdRoute,
  AppProblemsIndexRoute: AppProblemsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
