import { z } from 'zod';

export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_USERNAME_TAKEN: 'AUTH_USERNAME_TAKEN',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_USERNAME_TAKEN: 'USER_USERNAME_TAKEN',
  USER_BANNED: 'USER_BANNED',

  // Room
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_FULL: 'ROOM_FULL',
  ROOM_ALREADY_JOINED: 'ROOM_ALREADY_JOINED',
  ROOM_FINISHED: 'ROOM_FINISHED',
  ROOM_INVALID_TRANSITION: 'ROOM_INVALID_TRANSITION',
  ROOM_INVALID_CODE: 'ROOM_INVALID_CODE',
  ROOM_NOT_PARTICIPANT: 'ROOM_NOT_PARTICIPANT',
  ROOM_PERMISSION_DENIED: 'ROOM_PERMISSION_DENIED',
  ROOM_ACCESS_DENIED: 'ROOM_ACCESS_DENIED',
  ROOM_INVITE_CODE_EXHAUSTED: 'ROOM_INVITE_CODE_EXHAUSTED',
  ROOM_EDITOR_LOCKED: 'ROOM_EDITOR_LOCKED',
  ROOM_EDITOR_NOT_LOCKED: 'ROOM_EDITOR_NOT_LOCKED',
  ROOM_NOT_AI_MODE: 'ROOM_NOT_AI_MODE',
  ROOM_NOT_PEER_MODE: 'ROOM_NOT_PEER_MODE',
  ROOM_ROLE_UNAVAILABLE: 'ROOM_ROLE_UNAVAILABLE',
  ROOM_ROLE_CONSTRAINT_VIOLATION: 'ROOM_ROLE_CONSTRAINT_VIOLATION',

  // Role swap
  ROLE_SWAP_NOT_FOUND: 'ROLE_SWAP_NOT_FOUND',
  ROLE_SWAP_EXPIRED: 'ROLE_SWAP_EXPIRED',

  // Participant
  PARTICIPANT_NOT_FOUND: 'PARTICIPANT_NOT_FOUND',
  PARTICIPANT_CANNOT_CHANGE_ROLE: 'PARTICIPANT_CANNOT_CHANGE_ROLE',
  PARTICIPANT_CANNOT_TRANSFER_OWNERSHIP: 'PARTICIPANT_CANNOT_TRANSFER_OWNERSHIP',

  // Problem
  PROBLEM_NOT_FOUND: 'PROBLEM_NOT_FOUND',
  PROBLEM_DUPLICATE_TITLE: 'PROBLEM_DUPLICATE_TITLE',

  // Execution
  EXECUTION_JOB_NOT_FOUND: 'EXECUTION_JOB_NOT_FOUND',
  EXECUTION_RATE_LIMIT: 'EXECUTION_RATE_LIMIT',
  EXECUTION_SERVICE_UNAVAILABLE: 'EXECUTION_SERVICE_UNAVAILABLE',
  EXECUTION_SERVICE_TIMEOUT: 'EXECUTION_SERVICE_TIMEOUT',

  // Submission
  SUBMISSION_NOT_FOUND: 'SUBMISSION_NOT_FOUND',
  SUBMISSION_RATE_LIMIT: 'SUBMISSION_RATE_LIMIT',

  // AI
  AI_HINT_RATE_LIMIT: 'AI_HINT_RATE_LIMIT',
  AI_MESSAGE_RATE_LIMIT: 'AI_MESSAGE_RATE_LIMIT',
  AI_SERVICE_UNAVAILABLE: 'AI_SERVICE_UNAVAILABLE',

  // Feedback
  FEEDBACK_ALREADY_SUBMITTED: 'FEEDBACK_ALREADY_SUBMITTED',
  FEEDBACK_ROOM_NOT_FINISHED: 'FEEDBACK_ROOM_NOT_FINISHED',

  // Session
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_NOT_PARTICIPANT: 'SESSION_NOT_PARTICIPANT',
  SESSION_RECORDING_NOT_FOUND: 'SESSION_RECORDING_NOT_FOUND',
  SESSION_WHITEBOARD_NOT_FOUND: 'SESSION_WHITEBOARD_NOT_FOUND',
  SESSION_AI_MESSAGES_NOT_FOUND: 'SESSION_AI_MESSAGES_NOT_FOUND',
  SESSION_REPORT_NOT_READY: 'SESSION_REPORT_NOT_READY',

  // Matchmaking
  MATCH_ALREADY_SEARCHING: 'MATCH_ALREADY_SEARCHING',
  MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',
  MATCH_EXPIRED: 'MATCH_EXPIRED',

  // Recording
  RECORDING_ALREADY_ACTIVE: 'RECORDING_ALREADY_ACTIVE',
  RECORDING_NOT_ACTIVE: 'RECORDING_NOT_ACTIVE',
  RECORDING_CONSENT_MISSING: 'RECORDING_CONSENT_MISSING',

  // Analysis
  ANALYSIS_JOB_NOT_FOUND: 'ANALYSIS_JOB_NOT_FOUND',

  // Collab (internal)
  COLLAB_DOCUMENT_NOT_FOUND: 'COLLAB_DOCUMENT_NOT_FOUND',
  COLLAB_DOCUMENT_ALREADY_EXISTS: 'COLLAB_DOCUMENT_ALREADY_EXISTS',
  COLLAB_INVALID_REQUEST: 'COLLAB_INVALID_REQUEST',
  COLLAB_INTERNAL_ERROR: 'COLLAB_INTERNAL_ERROR',

  // System
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
const errorCodeValues = Object.values(ERROR_CODES) as [ErrorCode, ...ErrorCode[]];

export const errorResponseSchema = z.object({
  statusCode: z
    .number()
    .describe('HTTP status code')
    .meta({ examples: [500] }),
  code: z
    .enum(errorCodeValues)
    .optional()
    .describe('Machine-readable error code')
    .meta({ examples: [ERROR_CODES.AUTH_INVALID_CREDENTIALS] }),
  message: z
    .string()
    .describe('Human-readable error message')
    .meta({ examples: ['Internal server error'] }),
  timestamp: z
    .string()
    .datetime()
    .describe('ISO 8601 timestamp')
    .meta({ examples: ['2026-03-03T12:00:00.000Z'] }),
  details: z
    .record(z.string(), z.any())
    .optional()
    .describe(
      'Additional error details. For validation errors: per-field error info. ' +
        'For circuit breaker errors: circuit name and retry timing.',
    ),
});

export type ErrorResponse = z.infer<typeof errorResponseSchema>;
