export type ProblemDifficulty = 'Easy' | 'Medium' | 'Hard';
export type ProblemStatus = 'Solved' | 'Attempted' | 'Todo';
export type ProblemSortKey = 'newest' | 'acceptance' | 'difficulty';

export interface ProblemItem {
  id: string;
  title: string;
  difficulty: ProblemDifficulty;
  status: ProblemStatus;
  acceptanceRate: number;
  tags: string[];
  addedAt: number;
}

export const DIFFICULTY_OPTIONS: ProblemDifficulty[] = ['Easy', 'Medium', 'Hard'];
export const STATUS_OPTIONS: ProblemStatus[] = ['Solved', 'Attempted', 'Todo'];
export const TAG_OPTIONS = [
  'Arrays',
  'Strings',
  'DP',
  'Graphs',
  'Trees',
  'Hash Table',
  'Sliding Window',
  'Linked List',
] as const;

export const SORT_OPTIONS: Array<{ label: string; value: ProblemSortKey }> = [
  { label: 'Newest', value: 'newest' },
  { label: 'Acceptance rate', value: 'acceptance' },
  { label: 'Difficulty', value: 'difficulty' },
];

export const MOCK_PROBLEMS: ProblemItem[] = [
  {
    id: 'two-sum',
    title: 'Two Sum',
    difficulty: 'Easy',
    status: 'Solved',
    acceptanceRate: 67,
    tags: ['Arrays', 'Hash Table'],
    addedAt: 24,
  },
  {
    id: 'valid-parentheses',
    title: 'Valid Parentheses',
    difficulty: 'Easy',
    status: 'Solved',
    acceptanceRate: 72,
    tags: ['Strings', 'Stack'],
    addedAt: 23,
  },
  {
    id: 'merge-two-sorted-lists',
    title: 'Merge Two Sorted Lists',
    difficulty: 'Easy',
    status: 'Attempted',
    acceptanceRate: 74,
    tags: ['Linked List', 'Recursion'],
    addedAt: 22,
  },
  {
    id: 'longest-substring-without-repeating-characters',
    title: 'Longest Substring Without Repeating Characters',
    difficulty: 'Medium',
    status: 'Attempted',
    acceptanceRate: 45,
    tags: ['Strings', 'Sliding Window', 'Hash Table'],
    addedAt: 21,
  },
  {
    id: 'add-two-numbers',
    title: 'Add Two Numbers',
    difficulty: 'Medium',
    status: 'Todo',
    acceptanceRate: 52,
    tags: ['Linked List', 'Math', 'Recursion'],
    addedAt: 20,
  },
  {
    id: 'lru-cache',
    title: 'LRU Cache',
    difficulty: 'Medium',
    status: 'Todo',
    acceptanceRate: 41,
    tags: ['Hash Table', 'Design', 'Linked List'],
    addedAt: 19,
  },
  {
    id: 'binary-tree-level-order-traversal',
    title: 'Binary Tree Level Order Traversal',
    difficulty: 'Medium',
    status: 'Solved',
    acceptanceRate: 63,
    tags: ['Trees', 'BFS', 'Binary Tree'],
    addedAt: 18,
  },
  {
    id: 'course-schedule',
    title: 'Course Schedule',
    difficulty: 'Medium',
    status: 'Attempted',
    acceptanceRate: 48,
    tags: ['Graphs', 'Topological Sort', 'BFS', 'DFS'],
    addedAt: 17,
  },
  {
    id: 'merge-k-sorted-lists',
    title: 'Merge K Sorted Lists',
    difficulty: 'Hard',
    status: 'Todo',
    acceptanceRate: 34,
    tags: ['Linked List', 'Divide and Conquer', 'Heap'],
    addedAt: 16,
  },
  {
    id: 'trapping-rain-water',
    title: 'Trapping Rain Water',
    difficulty: 'Hard',
    status: 'Attempted',
    acceptanceRate: 28,
    tags: ['Arrays', 'Two Pointers', 'DP', 'Stack'],
    addedAt: 15,
  },
  {
    id: 'word-ladder',
    title: 'Word Ladder',
    difficulty: 'Hard',
    status: 'Todo',
    acceptanceRate: 31,
    tags: ['BFS', 'Hash Table', 'Strings'],
    addedAt: 14,
  },
  {
    id: 'serialize-and-deserialize-binary-tree',
    title: 'Serialize and Deserialize Binary Tree',
    difficulty: 'Hard',
    status: 'Todo',
    acceptanceRate: 36,
    tags: ['Trees', 'Design', 'BFS', 'DFS'],
    addedAt: 13,
  },
  {
    id: 'best-time-to-buy-and-sell-stock',
    title: 'Best Time to Buy and Sell Stock',
    difficulty: 'Easy',
    status: 'Solved',
    acceptanceRate: 54,
    tags: ['Arrays', 'DP'],
    addedAt: 12,
  },
  {
    id: 'maximum-subarray',
    title: 'Maximum Subarray',
    difficulty: 'Medium',
    status: 'Solved',
    acceptanceRate: 50,
    tags: ['Arrays', 'DP', 'Divide and Conquer'],
    addedAt: 11,
  },
  {
    id: 'container-with-most-water',
    title: 'Container With Most Water',
    difficulty: 'Medium',
    status: 'Attempted',
    acceptanceRate: 57,
    tags: ['Arrays', 'Two Pointers'],
    addedAt: 10,
  },
  {
    id: 'group-anagrams',
    title: 'Group Anagrams',
    difficulty: 'Medium',
    status: 'Solved',
    acceptanceRate: 59,
    tags: ['Hash Table', 'Strings', 'Sorting'],
    addedAt: 9,
  },
  {
    id: 'climbing-stairs',
    title: 'Climbing Stairs',
    difficulty: 'Easy',
    status: 'Solved',
    acceptanceRate: 53,
    tags: ['DP', 'Math'],
    addedAt: 8,
  },
  {
    id: 'coin-change',
    title: 'Coin Change',
    difficulty: 'Medium',
    status: 'Todo',
    acceptanceRate: 46,
    tags: ['DP', 'Arrays'],
    addedAt: 7,
  },
  {
    id: 'number-of-islands',
    title: 'Number of Islands',
    difficulty: 'Medium',
    status: 'Attempted',
    acceptanceRate: 58,
    tags: ['Graphs', 'DFS', 'BFS'],
    addedAt: 6,
  },
  {
    id: 'rotting-oranges',
    title: 'Rotting Oranges',
    difficulty: 'Medium',
    status: 'Todo',
    acceptanceRate: 49,
    tags: ['Graphs', 'BFS', 'Arrays'],
    addedAt: 5,
  },
  {
    id: 'same-tree',
    title: 'Same Tree',
    difficulty: 'Easy',
    status: 'Solved',
    acceptanceRate: 65,
    tags: ['Trees', 'DFS', 'Binary Tree'],
    addedAt: 4,
  },
  {
    id: 'diameter-of-binary-tree',
    title: 'Diameter of Binary Tree',
    difficulty: 'Easy',
    status: 'Attempted',
    acceptanceRate: 61,
    tags: ['Trees', 'DFS', 'Binary Tree'],
    addedAt: 3,
  },
  {
    id: 'edit-distance',
    title: 'Edit Distance',
    difficulty: 'Hard',
    status: 'Todo',
    acceptanceRate: 43,
    tags: ['DP', 'Strings'],
    addedAt: 2,
  },
  {
    id: 'minimum-window-substring',
    title: 'Minimum Window Substring',
    difficulty: 'Hard',
    status: 'Attempted',
    acceptanceRate: 39,
    tags: ['Strings', 'Sliding Window', 'Hash Table'],
    addedAt: 1,
  },
];
